// Copyright 2019 Fedotov Vlad
#ifndef MODULES_TASK_3_FEDOTOV_V_GLOBAL_OPTIMIZATION_GLOBAL_OPTIMIZATION_H_
#define MODULES_TASK_3_FEDOTOV_V_GLOBAL_OPTIMIZATION_GLOBAL_OPTIMIZATION_H_

#include <vector>
#include <string>


#endif  // MODULES_TASK_3_FEDOTOV_V_GLOBAL_OPTIMIZATION_GLOBAL_OPTIMIZATION_H_
